import { Stack, useRouter } from "expo-router";
import { useState } from "react";
import { KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import { createTracker } from "../src/api";
import { scheduleOptions } from "../src/schedule";
import { ActionButton, colors, Page } from "../src/ui";

const examples = ["Track when the new coastal rail line will reopen", "Follow the antitrust case against Acme Corp", "Track the recovery after the North Bay wildfire"];
export default function NewTrackerScreen() {
  const router = useRouter(); const [query, setQuery] = useState(""); const [pollIntervalMinutes, setPollIntervalMinutes] = useState(60); const [submitting, setSubmitting] = useState(false); const [error, setError] = useState<string | null>(null);
  const submit = async () => {
    if (!query.trim()) { setError("Describe a situation you want to track."); return; }
    setSubmitting(true); setError(null);
    try { const result = await createTracker(query, pollIntervalMinutes); router.replace({ pathname: "/tracker/[id]", params: { id: result.tracker.id } }); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Unable to create tracker"); }
    finally { setSubmitting(false); }
  };
  return <Page><Stack.Screen options={{ title: "New tracker", presentation: "modal" }} /><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === "ios" ? "padding" : undefined}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><Text style={styles.eyebrow}>ONE QUESTION</Text><Text style={styles.title}>What situation should Radar follow?</Text><Text style={styles.body}>Write naturally. You don’t need keywords, categories, or special syntax.</Text><TextInput accessibilityLabel="Situation to track" autoFocus multiline maxLength={1000} onChangeText={(value) => { setQuery(value); if (error) setError(null); }} placeholder="e.g. Track when the coastal rail line will reopen" placeholderTextColor="#8A938C" style={styles.input} value={query} /><Text style={styles.count}>{query.length}/1000</Text><Text style={styles.frequencyTitle}>How often should Radar check?</Text><View style={styles.frequencyOptions}>{scheduleOptions.map((option) => <Pressable accessibilityRole="radio" accessibilityState={{ checked: pollIntervalMinutes === option.minutes }} key={option.minutes} onPress={() => setPollIntervalMinutes(option.minutes)} style={[styles.frequencyOption, pollIntervalMinutes === option.minutes && styles.frequencySelected]}><Text style={[styles.frequencyText, pollIntervalMinutes === option.minutes && styles.frequencyTextSelected]}>{option.label}</Text></Pressable>)}</View>{error ? <Text accessibilityRole="alert" style={styles.error}>{error}</Text> : null}<ActionButton label={submitting ? "Starting baseline…" : "Start tracking"} disabled={submitting} onPress={() => void submit()} /><View style={styles.examples}><Text style={styles.examplesTitle}>Try an example</Text>{examples.map((example) => <Pressable key={example} onPress={() => setQuery(example)} style={styles.example}><Text style={styles.exampleText}>{example}</Text></Pressable>)}</View></ScrollView></KeyboardAvoidingView></Page>;
}
const styles = StyleSheet.create({ flex: { flex: 1 }, content: { padding: 24, paddingBottom: 48 }, eyebrow: { color: colors.accent, fontSize: 12, fontWeight: "900", letterSpacing: 2 }, title: { color: colors.ink, fontSize: 32, lineHeight: 38, fontWeight: "800", letterSpacing: -0.8, marginTop: 10 }, body: { color: colors.muted, fontSize: 16, lineHeight: 24, marginTop: 12 }, input: { minHeight: 150, marginTop: 24, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.line, borderRadius: 18, padding: 17, color: colors.ink, fontSize: 18, lineHeight: 27, textAlignVertical: "top" }, count: { color: colors.muted, fontSize: 12, textAlign: "right", marginVertical: 7 }, frequencyTitle: { color: colors.ink, fontSize: 16, fontWeight: "700", marginTop: 10, marginBottom: 10 }, frequencyOptions: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginBottom: 18 }, frequencyOption: { borderWidth: 1, borderColor: colors.line, backgroundColor: colors.surface, borderRadius: 999, paddingHorizontal: 14, paddingVertical: 10 }, frequencySelected: { backgroundColor: colors.ink, borderColor: colors.ink }, frequencyText: { color: colors.muted, fontWeight: "700" }, frequencyTextSelected: { color: colors.surface }, error: { color: colors.red, fontSize: 14, marginBottom: 10 }, examples: { marginTop: 30, gap: 9 }, examplesTitle: { color: colors.ink, fontWeight: "700", marginBottom: 2 }, example: { borderColor: colors.line, borderWidth: 1, borderRadius: 14, padding: 14, backgroundColor: "rgba(255,255,255,0.55)" }, exampleText: { color: colors.muted, fontSize: 14, lineHeight: 20 } });
